apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "social-ledger.fullname" . }}-config
  labels:
    {{- include "social-ledger.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ include "social-ledger.fullname" . }}-db:{{ .Values.db.port }}/{{ .Values.db.name }}"
  SPRING_JPA_HIBERNATE_DDL_AUTO: {{ .Values.api.jpaDdlAuto | quote }}
  API_HOST: "{{ include "social-ledger.fullname" . }}-api"
