db:
  image:
    repository: postgres
    tag: "15-alpine"
  name: socialledger
  user: postgres
  password: postgres
  port: 5432
  storage: 1Gi
  persistence:
    storageClass: social-ledger-manual
    reclaimPolicy: Retain
    hostPath: /data/social-ledger-db
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

api:
  image:
    repository: jpmrangel/social-ledger-api
    tag: "latest"
    pullPolicy: IfNotPresent
  port: 8080
  replicas: 1
  jpaDdlAuto: update
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"

frontend:
  image:
    repository: jpmrangel/social-ledger-frontend
    tag: "latest"
    pullPolicy: IfNotPresent
  port: 80
  replicas: 1
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

ingress:
  enabled: true
  className: nginx
  hosts:
    - k8s.local
  annotations: {}
