apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "social-ledger.fullname" . }}-db-pvc
  labels:
    {{- include "social-ledger.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.storage }}
