apiVersion: v1
kind: Service
metadata:
  name: {{ include "social-ledger.fullname" . }}-db
  labels:
    {{- include "social-ledger.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.db.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "social-ledger.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
